CREATE TABLE users (
 id NUMBER(19, 0) PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(255) UNIQUE,
 email_verified_at TIMESTAMP,
 password VARCHAR(255),
 image_path VARCHAR(255),
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
